# Generated by Django 3.2.6 on 2021-08-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Work', models.CharField(max_length=20)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
