# Generated by Django 3.2.6 on 2021-09-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='idPerson',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='Salary',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
